# Generated by Django 4.2.3 on 2023-10-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emo_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_user_id", models.CharField(max_length=255, unique=True)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
