# Generated by Django 4.2.3 on 2023-11-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emo_core", "0006_temporarycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempregister",
            name="line_user_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tempregister",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
