# Generated by Django 4.2.3 on 2023-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emo_core", "0007_alter_tempregister_line_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempRegisterToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_user_id", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("expiration", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="TempRegister",
        ),
    ]
